#!/bin/bash
#
# Author: Cyril GENISSON
# Created: 10/10/2023
# Updated: 13/10/2023
#
# Nom du script: alcasar_login
# Description: Crée une nouvelle connexion sur le portail captif alcasar.laplateforme.io
#
#set -x

EMAIL=$1
PASSWD=$2

if [ -z $EMAIL ] && [ -z $PASSWD ] ; then
    echo "$0 EMAIL PASSWORD"
    exit 1
fi

URI="https://alcasar.laplateforme.io/intercept.php"
CHALLENGE=$(curl -I https://alcasar.laplateforme.io:3991/prelogin | grep ^Location | cut -d'&' -f4)
CHAL=$(echo -n $CHALLENGE | cut -d '=' -f2)
# Données sous format brut
#DATAS="$CHALLENGE&username=$EMAIL&password=$PASSWD&button=Authentification"
# Données sous format JSON
#DATA={\"challenge\":\"$CHAL\",\"username\":\"$EMAIL\",\"password\":\"$PASSWD\",\"button\":\"Authentification\"}
#LENGTH=$(echo -n $DATA | wc -c)

#curl -XL POST \
#    --url $URI \
#    --location $URI \
#    --header "Content-Type: application/json" \
#    --header "Content-Length: length=$LENGTH" \
#    -d $DATA

######################################################
# Une Bonne version de la requête à ne pas toucher
# ###################################################
curl  --request POST \
--url $URI  \
--location $URI \
--header "Content-Type: multipart/form-data" \
--form username=$EMAIL \
--form password=$PASSWD \
--form $CHALLENGE \
--form button=Authentication > /dev/null

echo "Connexion établie"

exit 0
